### ISSUE TITLE
how can I  reverse the transaction

### ISSUE THREAD

**Issue by yezl77** [ChimeraCoder/mgo#1]
I have a problem ,if I have a transaction id ,and it has applied,(state and db),how can I reverse the transaction,and remove the transaction from tc and tc.stash

**Comment by acpyin** [comment]
I am reading your code ,but something I can't understand.

**Comment by ChimeraCoder** [comment]
This is just a git mirror of the original mgo library - I'd suggest filing an issue with that project.
